/**
 * Latest-docs slugs that moved in the 3.0 rewrite, mapped to their new home.
 * The site ships as a static export, so each old slug is prerendered as a
 * redirect page (Next emits a meta refresh). Archived versions keep their own
 * URLs and never go through this map.
 */
export const LATEST_DOC_REDIRECTS: Record<string, string> = {
  tao: 'windows',
  'tao/decorated-window': 'windows',
  'tao/window-scaffold': 'windows/window-scaffold',
  'tao/overlay-windows': 'windows/overlay-windows',
  'tao/wayland': 'windows/linux-wayland',
  'tao/hidpi': 'windows/hidpi',
  'tao/multi-touch': 'input/trackpad-gestures',
  'tao/pen-stylus': 'input/pen-stylus',
  'tao/drag-and-drop': 'input/drag-and-drop',
  'tao/accessibility': 'input/accessibility',
  'tao/native-views': 'native-content/native-views',
  'tao/texture-view': 'native-content/texture-view',
  'tao/gpu-render-context': 'native-content/gpu-render-context',
  'tao/taskbar-progress': 'os/dock-taskbar/progress',
  'tao/migration-from-jbr': 'migrate/from-2.x',
  'concepts/backends': 'migrate/from-2.x',
  'performance/native-access': 'performance/graalvm/automatic-metadata',
  'concepts/runtimes': 'performance',
  'why-nucleus': '',
  'start/project-setup': 'start/install',
  'migrate/from-1.x': '2.5/migrate/from-1.x',
  ecosystem: 'os/file-dialogs',
  'ecosystem/file-dialog': 'os/file-dialogs',
  'os/notification-macos': 'os/notifications/macos',
  'os/notification-windows': 'os/notifications/windows',
  'os/notification-linux': 'os/notifications/linux',
  'os/system-tray': 'os/tray',
  'os/tray-menu-dsl': 'os/tray/menu',
  'os/tray-app': 'os/tray/tray-app',
  'lifecycle/launcher-macos': 'os/dock-taskbar/macos',
  'lifecycle/launcher-windows': 'os/dock-taskbar/windows',
  'lifecycle/launcher-linux': 'os/dock-taskbar/linux',
  'lifecycle/taskbar-progress': 'os/dock-taskbar/progress',
  'os/menu-macos': 'os/menus/menu-bar',
  'windows/context-menu': 'os/menus/context-menu',
  'os/sf-symbols': 'os/icons/sf-symbols',
  'os/freedesktop-icons': 'os/icons/freedesktop',
  'os/dark-mode': 'os/theme/dark-mode',
  'os/system-color': 'os/theme/accent-color',
  'lifecycle/auto-launch': 'lifecycle/background/launch-at-login',
  'lifecycle/scheduler': 'lifecycle/background/scheduler',
  'lifecycle/scheduler-testing': 'lifecycle/background/scheduler-testing',
  'lifecycle/service-management': 'lifecycle/background/service-management',
  window: 'windows',
  'window/context-menu': 'os/menus/context-menu',
  'window/toolkits': 'toolkits',
  'window/toolkit-macos': 'toolkits/macos',
  'window/toolkit-fluent': 'toolkits/fluent',
  'window/toolkit-yaru': 'toolkits/yaru',
  'window/toolkit-jewel': 'toolkits/jewel',
  'window/toolkit-material': 'toolkits/material',
};
